<?php

namespace Pygments;

class PygmentizeTest extends \PHPUnit_Framework_TestCase
{
    public function testVersion()
    {
        $this->assertEquals("1.6", Pygmentize::version());
    }

    public function testLexers()
    {
        $this->assertEquals(
            array (
                'Clipper' => 'FoxPro ',
                'XBase' => 'FoxPro ',
                'Cucumber' => 'Gherkin ',
                'cucumber' => 'Gherkin ',
                'Gherkin' => 'Gherkin ',
                'gherkin' => 'Gherkin ',
                'RobotFramework' => 'RobotFramework ',
                'robotframework' => 'RobotFramework ',
                'abap' => 'ABAP ',
                'ada' => 'Ada ',
                'ada95ada2005' => 'Ada ',
                'ahk' => 'autohotkey ',
                'antlr-as' => 'ANTLR With ActionScript Target ',
                'antlr-actionscript' => 'ANTLR With ActionScript Target ',
                'antlr-cpp' => 'ANTLR With CPP Target ',
                'antlr-csharp' => 'ANTLR With C# Target ',
                'antlr-c#' => 'ANTLR With C# Target ',
                'antlr-java' => 'ANTLR With Java Target ',
                'antlr-objc' => 'ANTLR With ObjectiveC Target ',
                'antlr-perl' => 'ANTLR With Perl Target ',
                'antlr-python' => 'ANTLR With Python Target ',
                'antlr-ruby' => 'ANTLR With Ruby Target ',
                'antlr-rb' => 'ANTLR With Ruby Target ',
                'antlr' => 'ANTLR',
                'apacheconf' => 'ApacheConf ',
                'aconf' => 'ApacheConf ',
                'apache' => 'ApacheConf ',
                'applescript' => 'AppleScript ',
                'as' => 'ActionScript ',
                'actionscript' => 'ActionScript ',
                'as3' => 'ActionScript 3 ',
                'actionscript3' => 'ActionScript 3 ',
                'aspectj' => 'AspectJ ',
                'aspx-cs' => 'aspx-cs ',
                'aspx-vb' => 'aspx-vb ',
                'asy' => 'Asymptote ',
                'asymptote' => 'Asymptote ',
                'autoit' => 'AutoIt ',
                'Autoit' => 'AutoIt ',
                'awk' => 'Awk ',
                'gawk' => 'Awk ',
                'mawk' => 'Awk ',
                'nawk' => 'Awk ',
                'basemake' => 'Base Makefile',
                'bash' => 'Bash ',
                'sh' => 'Bash ',
                'ksh' => 'Bash ',
                'bat' => 'Batchfile ',
                'bbcode' => 'BBCode',
                'befunge' => 'Befunge ',
                'blitzmax' => 'BlitzMax ',
                'bmax' => 'BlitzMax ',
                'boo' => 'Boo ',
                'brainfuck' => 'Brainfuck ',
                'bf' => 'Brainfuck ',
                'bro' => 'Bro ',
                'bugs' => 'BUGS ',
                'winbugs' => 'BUGS ',
                'openbugs' => 'BUGS ',
                'c-objdump' => 'c-objdump ',
                'c' => 'C ',
                'ca65' => 'ca65 ',
                'cbmbas' => 'CBM BASIC V2 ',
                'ceylon' => 'Ceylon ',
                'cfengine3' => 'CFEngine3 ',
                'cf3' => 'CFEngine3 ',
                'cfm' => 'Coldfusion HTML ',
                'cfs' => 'cfstatement',
                'cheetah' => 'Cheetah ',
                'spitfire' => 'Cheetah ',
                'clojure' => 'Clojure ',
                'clj' => 'Clojure ',
                'cmake' => 'CMake ',
                'cobol' => 'COBOL ',
                'cobolfree' => 'COBOLFree ',
                'coffee-script' => 'CoffeeScript ',
                'coffeescript' => 'CoffeeScript ',
                'common-lisp' => 'Common Lisp ',
                'cl' => 'Common Lisp ',
                'console' => 'Bash Session ',
                'control' => 'Debian Control file ',
                'coq' => 'Coq ',
                'cpp' => 'C++ ',
                'c++' => 'C++ ',
                'cpp-objdump' => 'cpp-objdump ',
                'c++-objdumb' => 'cpp-objdump ',
                'cxx-objdump' => 'cpp-objdump ',
                'croc' => 'Croc ',
                'csharp' => 'C# ',
                'c#' => 'C# ',
                'css+django' => 'CSS+Django/Jinja',
                'css+jinja' => 'CSS+Django/Jinja',
                'css+erb' => 'CSS+Ruby',
                'css+ruby' => 'CSS+Ruby',
                'css+genshitext' => 'CSS+Genshi Text',
                'css+genshi' => 'CSS+Genshi Text',
                'css+lasso' => 'CSS+Lasso',
                'css+mako' => 'CSS+Mako',
                'css+myghty' => 'CSS+Myghty',
                'css+php' => 'CSS+PHP',
                'css+smarty' => 'CSS+Smarty',
                'css' => 'CSS ',
                'cuda' => 'CUDA ',
                'cu' => 'CUDA ',
                'cython' => 'Cython ',
                'pyx' => 'Cython ',
                'd-objdump' => 'd-objdump ',
                'd' => 'D ',
                'dart' => 'Dart ',
                'delphi' => 'Delphi ',
                'pas' => 'Delphi ',
                'pascal' => 'Delphi ',
                'objectpascal' => 'Delphi ',
                'dg' => 'dg ',
                'diff' => 'Diff ',
                'udiff' => 'Diff ',
                'django' => 'Django/Jinja',
                'jinja' => 'Django/Jinja',
                'dpatch' => 'Darcs Patch ',
                'dtd' => 'DTD ',
                'duel' => 'Duel ',
                'Duel Engine' => 'Duel ',
                'Duel View' => 'Duel ',
                'JBST' => 'Duel ',
                'jbst' => 'Duel ',
                'JsonML+BST' => 'Duel ',
                'dylan-console' => 'Dylan session ',
                'dylan-repl' => 'Dylan session ',
                'dylan-lid' => 'DylanLID ',
                'lid' => 'DylanLID ',
                'dylan' => 'Dylan ',
                'ec' => 'eC ',
                'ecl' => 'ECL ',
                'elixir' => 'Elixir ',
                'ex' => 'Elixir ',
                'exs' => 'Elixir ',
                'erb' => 'ERB',
                'erl' => 'Erlang erl session ',
                'erlang' => 'Erlang ',
                'evoque' => 'Evoque ',
                'factor' => 'Factor ',
                'fan' => 'Fantom ',
                'fancy' => 'Fancy ',
                'fy' => 'Fancy ',
                'felix' => 'Felix ',
                'flx' => 'Felix ',
                'fortran' => 'Fortran ',
                'fsharp' => 'FSharp ',
                'gas' => 'GAS ',
                'genshi' => 'Genshi ',
                'kid' => 'Genshi ',
                'xml+genshi' => 'Genshi ',
                'xml+kid' => 'Genshi ',
                'genshitext' => 'Genshi Text',
                'glsl' => 'GLSL ',
                'gnuplot' => 'Gnuplot ',
                'go' => 'Go ',
                'gooddata-cl' => 'GoodData-CL ',
                'gosu' => 'Gosu ',
                'groff' => 'Groff ',
                'nroff' => 'Groff ',
                'man' => 'Groff ',
                'groovy' => 'Groovy ',
                'gst' => 'Gosu Template ',
                'haml' => 'Haml ',
                'HAML' => 'Haml ',
                'haskell' => 'Haskell ',
                'hs' => 'Haskell ',
                'haxeml' => 'Hxml ',
                'hxml' => 'Hxml ',
                'html+cheetah' => 'HTML+Cheetah',
                'html+spitfire' => 'HTML+Cheetah',
                'html+django' => 'HTML+Django/Jinja',
                'html+jinja' => 'HTML+Django/Jinja',
                'html+evoque' => 'HTML+Evoque ',
                'html+genshi' => 'HTML+Genshi',
                'html+kid' => 'HTML+Genshi',
                'html+lasso' => 'HTML+Lasso',
                'html+mako' => 'HTML+Mako',
                'html+myghty' => 'HTML+Myghty',
                'html+php' => 'HTML+PHP ',
                'html+smarty' => 'HTML+Smarty',
                'html+velocity' => 'HTML+Velocity',
                'html' => 'HTML ',
                'http' => 'HTTP',
                'hx' => 'haXe ',
                'haXe' => 'haXe ',
                'hybris' => 'Hybris ',
                'hy' => 'Hybris ',
                'idl' => 'IDL ',
                'iex' => 'Elixir iex session',
                'ini' => 'INI ',
                'cfg' => 'INI ',
                'io' => 'Io ',
                'ioke' => 'Ioke ',
                'ik' => 'Ioke ',
                'irc' => 'IRC logs ',
                'jade' => 'Jade ',
                'JADE' => 'Jade ',
                'jags' => 'JAGS ',
                'java' => 'Java ',
                'jlcon' => 'Julia console',
                'js+cheetah' => 'JavaScript+Cheetah',
                'javascript+cheetah' => 'JavaScript+Cheetah',
                'js+spitfire' => 'JavaScript+Cheetah',
                'javascript+spitfire' => 'JavaScript+Cheetah',
                'js+django' => 'JavaScript+Django/Jinja',
                'javascript+django' => 'JavaScript+Django/Jinja',
                'js+jinja' => 'JavaScript+Django/Jinja',
                'javascript+jinja' => 'JavaScript+Django/Jinja',
                'js+erb' => 'JavaScript+Ruby',
                'javascript+erb' => 'JavaScript+Ruby',
                'js+ruby' => 'JavaScript+Ruby',
                'javascript+ruby' => 'JavaScript+Ruby',
                'js+genshitext' => 'JavaScript+Genshi Text',
                'js+genshi' => 'JavaScript+Genshi Text',
                'javascript+genshitext' => 'JavaScript+Genshi Text',
                'javascript+genshi' => 'JavaScript+Genshi Text',
                'js+lasso' => 'JavaScript+Lasso',
                'javascript+lasso' => 'JavaScript+Lasso',
                'js+mako' => 'JavaScript+Mako',
                'javascript+mako' => 'JavaScript+Mako',
                'js+myghty' => 'JavaScript+Myghty',
                'javascript+myghty' => 'JavaScript+Myghty',
                'js+php' => 'JavaScript+PHP',
                'javascript+php' => 'JavaScript+PHP',
                'js+smarty' => 'JavaScript+Smarty',
                'javascript+smarty' => 'JavaScript+Smarty',
                'js' => 'JavaScript ',
                'javascript' => 'JavaScript ',
                'json' => 'JSON ',
                'jsp' => 'Java Server Page ',
                'julia' => 'Julia ',
                'jl' => 'Julia ',
                'kconfig' => 'Kconfig ',
                'menuconfig' => 'Kconfig ',
                'linux-config' => 'Kconfig ',
                'kernel-config' => 'Kconfig ',
                'koka' => 'Koka ',
                'kotlin' => 'Kotlin ',
                'lasso' => 'Lasso ',
                'lassoscript' => 'Lasso ',
                'lhs' => 'Literate Haskell ',
                'literate-haskell' => 'Literate Haskell ',
                'lighty' => 'Lighttpd configuration file',
                'lighttpd' => 'Lighttpd configuration file',
                'live-script' => 'LiveScript ',
                'livescript' => 'LiveScript ',
                'llvm' => 'LLVM ',
                'logos' => 'Logos ',
                'logtalk' => 'Logtalk ',
                'lua' => 'Lua ',
                'make' => 'Makefile ',
                'makefile' => 'Makefile ',
                'mf' => 'Makefile ',
                'bsdmake' => 'Makefile ',
                'mako' => 'Mako ',
                'maql' => 'MAQL ',
                'mason' => 'Mason ',
                'matlab' => 'Matlab ',
                'matlabsession' => 'Matlab session',
                'minid' => 'MiniD ',
                'modelica' => 'Modelica ',
                'modula2' => 'Modula-2 ',
                'm2' => 'Modula-2 ',
                'monkey' => 'Monkey ',
                'moocode' => 'MOOCode ',
                'moon' => 'MoonScript ',
                'moonscript' => 'MoonScript ',
                'mscgen' => 'Mscgen ',
                'msc' => 'Mscgen ',
                'mupad' => 'MuPAD ',
                'mxml' => 'MXML ',
                'myghty' => 'Myghty ',
                'mysql' => 'MySQL',
                'nasm' => 'NASM ',
                'nemerle' => 'Nemerle ',
                'newlisp' => 'NewLisp ',
                'newspeak' => 'Newspeak ',
                'nginx' => 'Nginx configuration file',
                'nimrod' => 'Nimrod ',
                'nim' => 'Nimrod ',
                'nsis' => 'NSIS ',
                'nsi' => 'NSIS ',
                'nsh' => 'NSIS ',
                'numpy' => 'NumPy',
                'objdump' => 'objdump ',
                'objective-c++' => 'Objective-C++ ',
                'objectivec++' => 'Objective-C++ ',
                'obj-c++' => 'Objective-C++ ',
                'objc++' => 'Objective-C++ ',
                'objective-c' => 'Objective-C ',
                'objectivec' => 'Objective-C ',
                'obj-c' => 'Objective-C ',
                'objc' => 'Objective-C ',
                'objective-j' => 'Objective-J ',
                'objectivej' => 'Objective-J ',
                'obj-j' => 'Objective-J ',
                'objj' => 'Objective-J ',
                'ocaml' => 'OCaml ',
                'octave' => 'Octave ',
                'ooc' => 'Ooc ',
                'opa' => 'Opa ',
                'openedge' => 'OpenEdge ABL ',
                'abl' => 'OpenEdge ABL ',
                'progress' => 'OpenEdge ABL ',
                'perl' => 'Perl ',
                'pl' => 'Perl ',
                'php' => 'PHP ',
                'php3' => 'PHP ',
                'php4' => 'PHP ',
                'php5' => 'PHP ',
                'plpgsql' => 'PL/pgSQL',
                'postgresql' => 'PostgreSQL SQL dialect',
                'postgres' => 'PostgreSQL SQL dialect',
                'postscript' => 'PostScript ',
                'pot' => 'Gettext Catalog ',
                'po' => 'Gettext Catalog ',
                'pov' => 'POVRay ',
                'powershell' => 'PowerShell ',
                'posh' => 'PowerShell ',
                'ps1' => 'PowerShell ',
                'prolog' => 'Prolog ',
                'properties' => 'Properties ',
                'protobuf' => 'Protocol Buffer ',
                'psql' => 'PostgreSQL console ',
                'postgresql-console' => 'PostgreSQL console ',
                'postgres-console' => 'PostgreSQL console ',
                'puppet' => 'Puppet ',
                'py3tb' => 'Python 3.0 Traceback ',
                'pycon' => 'Python console session',
                'pypylog' => 'PyPy Log ',
                'pypy' => 'PyPy Log ',
                'pytb' => 'Python Traceback ',
                'python' => 'Python ',
                'py' => 'Python ',
                'sage' => 'Python ',
                'python3' => 'Python 3',
                'py3' => 'Python 3',
                'qml' => 'QML ',
                'Qt Meta Language' => 'QML ',
                'Qt modeling Language' => 'QML ',
                'racket' => 'Racket ',
                'rkt' => 'Racket ',
                'ragel-c' => 'Ragel in C Host ',
                'ragel-cpp' => 'Ragel in CPP Host ',
                'ragel-d' => 'Ragel in D Host ',
                'ragel-em' => 'Embedded Ragel ',
                'ragel-java' => 'Ragel in Java Host ',
                'ragel-objc' => 'Ragel in Objective C Host ',
                'ragel-ruby' => 'Ragel in Ruby Host ',
                'ragel-rb' => 'Ragel in Ruby Host ',
                'ragel' => 'Ragel',
                'raw' => 'Raw token data',
                'rb' => 'Ruby ',
                'ruby' => 'Ruby ',
                'duby' => 'Ruby ',
                'rbcon' => 'Ruby irb session',
                'irb' => 'Ruby irb session',
                'rconsole' => 'RConsole ',
                'rout' => 'RConsole ',
                'rd' => 'Rd ',
                'rebol' => 'REBOL ',
                'redcode' => 'Redcode ',
                'registry' => 'reg ',
                'rhtml' => 'RHTML ',
                'html+erb' => 'RHTML ',
                'html+ruby' => 'RHTML ',
                'rst' => 'reStructuredText ',
                'rest' => 'reStructuredText ',
                'restructuredtext' => 'reStructuredText ',
                'rust' => 'Rust ',
                'sass' => 'Sass ',
                'SASS' => 'Sass ',
                'scala' => 'Scala ',
                'scaml' => 'Scaml ',
                'SCAML' => 'Scaml ',
                'scheme' => 'Scheme ',
                'scm' => 'Scheme ',
                'scilab' => 'Scilab ',
                'scss' => 'SCSS ',
                'shell-session' => 'Shell Session ',
                'smali' => 'Smali ',
                'smalltalk' => 'Smalltalk ',
                'squeak' => 'Smalltalk ',
                'smarty' => 'Smarty ',
                'sml' => 'Standard ML ',
                'snobol' => 'Snobol ',
                'sourceslist' => 'Debian Sourcelist ',
                'sources.list' => 'Debian Sourcelist ',
                'sp' => 'SourcePawn ',
                'spec' => 'RPMSpec ',
                'splus' => 'S ',
                's' => 'S ',
                'r' => 'S ',
                'sql' => 'SQL ',
                'sqlite3' => 'sqlite3con ',
                'squidconf' => 'SquidConf ',
                'squid.conf' => 'SquidConf ',
                'squid' => 'SquidConf ',
                'ssp' => 'Scalate Server Page ',
                'stan' => 'Stan ',
                'systemverilog' => 'systemverilog ',
                'sv' => 'systemverilog ',
                'tcl' => 'Tcl ',
                'tcsh' => 'Tcsh ',
                'csh' => 'Tcsh ',
                'tea' => 'Tea ',
                'tex' => 'TeX ',
                'latex' => 'TeX ',
                'text' => 'Text only ',
                'trac-wiki' => 'MoinMoin/Trac Wiki markup',
                'moin' => 'MoinMoin/Trac Wiki markup',
                'treetop' => 'Treetop ',
                'ts' => 'TypeScript ',
                'urbiscript' => 'UrbiScript ',
                'vala' => 'Vala ',
                'vapi' => 'Vala ',
                'vb.net' => 'VB.net ',
                'vbnet' => 'VB.net ',
                'velocity' => 'Velocity ',
                'verilog' => 'verilog ',
                'v' => 'verilog ',
                'vgl' => 'VGL ',
                'vhdl' => 'vhdl ',
                'vim' => 'VimL ',
                'xml+cheetah' => 'XML+Cheetah',
                'xml+spitfire' => 'XML+Cheetah',
                'xml+django' => 'XML+Django/Jinja',
                'xml+jinja' => 'XML+Django/Jinja',
                'xml+erb' => 'XML+Ruby',
                'xml+ruby' => 'XML+Ruby',
                'xml+evoque' => 'XML+Evoque ',
                'xml+lasso' => 'XML+Lasso',
                'xml+mako' => 'XML+Mako',
                'xml+myghty' => 'XML+Myghty',
                'xml+php' => 'XML+PHP',
                'xml+smarty' => 'XML+Smarty',
                'xml+velocity' => 'XML+Velocity',
                'xml' => 'XML ',
                'xquery' => 'XQuery ',
                'xqy' => 'XQuery ',
                'xq' => 'XQuery ',
                'xql' => 'XQuery ',
                'xqm' => 'XQuery ',
                'xslt' => 'XSLT ',
                'xtend' => 'Xtend ',
                'yaml' => 'YAML ',
            ),
            Pygmentize::lexers());
    }

    public function testStyles()
    {
        $this->assertEquals(array (
            'monokai' => 'This style mimics the Monokai color scheme.',
            'manni' => 'A colorful style, inspired by the terminal highlighting style.',
            'rrt' => 'Minimalistic "rrt" theme, based on Zap and Emacs defaults.',
            'perldoc' => 'Style similar to the style used in the perldoc code blocks.',
            'borland' => 'Style similar to the style used in the borland IDEs.',
            'colorful' => 'A colorful style, inspired by CodeRay.',
            'default' => 'The default style (inspired by Emacs 22).',
            'murphy' => 'Murphy\'s style from CodeRay.',
            'vs' => '* trac:',
            'tango' => 'The Crunchy default Style inspired from the color palette from the Tango Icon Theme Guidelines.',
            'fruity' => 'Pygments version of the "native" vim theme.',
            'autumn' => 'A colorful style, inspired by the terminal highlighting style.',
            'bw' => '* emacs:',
            'vim' => 'Styles somewhat like vim 7.0',
            'pastie' => 'Style similar to the pastie default style.',
            'friendly' => 'A modern style based on the VIM pyte theme.',
            'native' => 'Pygments version of the "native" vim theme.',
        ),
            Pygmentize::styles());
    }

    public function testGetStyle()
    {
        $this->assertEquals(".hll { background-color: #ffffcc }
.c { color: #0099FF; font-style: italic } /* Comment */
.err { color: #AA0000; background-color: #FFAAAA } /* Error */
.k { color: #006699; font-weight: bold } /* Keyword */
.o { color: #555555 } /* Operator */
.cm { color: #0099FF; font-style: italic } /* Comment.Multiline */
.cp { color: #009999 } /* Comment.Preproc */
.c1 { color: #0099FF; font-style: italic } /* Comment.Single */
.cs { color: #0099FF; font-weight: bold; font-style: italic } /* Comment.Special */
.gd { background-color: #FFCCCC; border: 1px solid #CC0000 } /* Generic.Deleted */
.ge { font-style: italic } /* Generic.Emph */
.gr { color: #FF0000 } /* Generic.Error */
.gh { color: #003300; font-weight: bold } /* Generic.Heading */
.gi { background-color: #CCFFCC; border: 1px solid #00CC00 } /* Generic.Inserted */
.go { color: #AAAAAA } /* Generic.Output */
.gp { color: #000099; font-weight: bold } /* Generic.Prompt */
.gs { font-weight: bold } /* Generic.Strong */
.gu { color: #003300; font-weight: bold } /* Generic.Subheading */
.gt { color: #99CC66 } /* Generic.Traceback */
.kc { color: #006699; font-weight: bold } /* Keyword.Constant */
.kd { color: #006699; font-weight: bold } /* Keyword.Declaration */
.kn { color: #006699; font-weight: bold } /* Keyword.Namespace */
.kp { color: #006699 } /* Keyword.Pseudo */
.kr { color: #006699; font-weight: bold } /* Keyword.Reserved */
.kt { color: #007788; font-weight: bold } /* Keyword.Type */
.m { color: #FF6600 } /* Literal.Number */
.s { color: #CC3300 } /* Literal.String */
.na { color: #330099 } /* Name.Attribute */
.nb { color: #336666 } /* Name.Builtin */
.nc { color: #00AA88; font-weight: bold } /* Name.Class */
.no { color: #336600 } /* Name.Constant */
.nd { color: #9999FF } /* Name.Decorator */
.ni { color: #999999; font-weight: bold } /* Name.Entity */
.ne { color: #CC0000; font-weight: bold } /* Name.Exception */
.nf { color: #CC00FF } /* Name.Function */
.nl { color: #9999FF } /* Name.Label */
.nn { color: #00CCFF; font-weight: bold } /* Name.Namespace */
.nt { color: #330099; font-weight: bold } /* Name.Tag */
.nv { color: #003333 } /* Name.Variable */
.ow { color: #000000; font-weight: bold } /* Operator.Word */
.w { color: #bbbbbb } /* Text.Whitespace */
.mf { color: #FF6600 } /* Literal.Number.Float */
.mh { color: #FF6600 } /* Literal.Number.Hex */
.mi { color: #FF6600 } /* Literal.Number.Integer */
.mo { color: #FF6600 } /* Literal.Number.Oct */
.sb { color: #CC3300 } /* Literal.String.Backtick */
.sc { color: #CC3300 } /* Literal.String.Char */
.sd { color: #CC3300; font-style: italic } /* Literal.String.Doc */
.s2 { color: #CC3300 } /* Literal.String.Double */
.se { color: #CC3300; font-weight: bold } /* Literal.String.Escape */
.sh { color: #CC3300 } /* Literal.String.Heredoc */
.si { color: #AA0000 } /* Literal.String.Interpol */
.sx { color: #CC3300 } /* Literal.String.Other */
.sr { color: #33AAAA } /* Literal.String.Regex */
.s1 { color: #CC3300 } /* Literal.String.Single */
.ss { color: #FFCC33 } /* Literal.String.Symbol */
.bp { color: #336666 } /* Name.Builtin.Pseudo */
.vc { color: #003333 } /* Name.Variable.Class */
.vg { color: #003333 } /* Name.Variable.Global */
.vi { color: #003333 } /* Name.Variable.Instance */
.il { color: #FF6600 } /* Literal.Number.Integer.Long */", Pygmentize::getStyle('manni'));
    }

    public function testFormat()
    {
        $source = '<html><head></head>
<body class="body"></body></html>';
        $lexer = 'html+php';
        $this->assertEquals(
            '<span class="nt">&lt;html&gt;&lt;head&gt;&lt;/head&gt;</span>
<span class="nt">&lt;body</span> <span class="na">class=</span><span class="s">&quot;body&quot;</span><span class="nt">&gt;&lt;/body&gt;&lt;/html&gt;</span>',
            Pygmentize::format($source, $lexer));
    }
}
